name: Deploy Img Server

on:
  push:
    branches: ['**']
    paths: [img-server/**]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:
      - uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Upload to FTP
        run: |
          lftp -c "
            set ftp:ssl-force true;
            set ftp:ssl-protect-data true;
            set ssl:verify-certificate false;
            open -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }};
            mirror --reverse --delete --exclude img/ --verbose ./img-server/ ${{ vars.FTP_DIR_IMG }};
          "
